// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 13/1/2026, 11:12:25 am
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/apple/Sites/Saloo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Sites/Saloo/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Sites/Saloo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Sites/Saloo/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Sites/Saloo/plugins/**/*.{js,ts,mjs}","/Users/apple/Sites/Saloo/composables/**/*.{js,ts,mjs}","/Users/apple/Sites/Saloo/utils/**/*.{js,ts,mjs}","/Users/apple/Sites/Saloo/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Sites/Saloo/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Sites/Saloo/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Sites/Saloo/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["17"] = "/Users/apple/Sites/Saloo/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;